strategy_code: S23
unique_code: NIFTY_OP_SELL_WK_DIFF_2D_3D_BULL_PUT
symbol: NIFTY
segment: OPTIONS_SELL
expiry_type: WEEKLY
rollover_policy: T_MINUS_1
forced_close_time: "12:00:00"
no_carry_past_expiry: true
allowed_monthly_statuses:
  - BULL
  - BULL_CF
option_type: PUT
entry_time: "09:24:59"
recalculation_time: "09:29:59"
minimum_oi: 32500
carry_forward_allowed: true
allow_fresh_entry_with_open_position: false
