"""Offline backtesting helpers for TradingEngineTFIS."""

from .backtest_runner import BacktestRunner
from .cost_model import CostModel
from .contract_intraday import (
    ContractIntradayBar,
    build_contract_intraday_lookup,
    load_contract_intraday_bars_csv,
    resolve_contract_intraday_bars,
)
from .csv_loader import (
    BacktestCsvError,
    OptionLevelsSnapshot,
    load_daily_bars_csv,
    load_intraday_option_bars_csv,
    load_intraday_spot_bars_csv,
    load_option_levels_csv,
    load_option_levels_series_csv,
)
from .historical_runner import (
    HistoricalBacktestMetrics,
    HistoricalBacktestReport,
    HistoricalBacktestRunner,
    HistoricalCandidateResult,
    HistoricalMarketSnapshot,
)
from .entry_missed import EntryMissedInput, EntryMissedResult, S23EntryMissedDetector
from .expiry_day import (
    ExpiryDayLifecycleReview,
    build_expiry_day_lifecycle_review,
)
from .metrics import build_backtest_metrics
from .models import BacktestInput, BacktestMetrics, BacktestTradeResult, BacktestValidation
from .parameter_sweep import (
    ParameterSweepRankingEntry,
    ParameterSweepReport,
    ParameterSweepRunner,
    ParameterSweepSummary,
    ParameterSweepTradeOutputs,
    ParameterSweepVariantResult,
    build_parameter_sweep_ranking,
    calculate_risk_reward_metrics,
    generate_parameter_combinations,
    render_parameter_sweep_markdown,
    sample_daily_bars,
    sample_runtime_values,
)
from .report_comparison import (
    BacktestReportComparisonError,
    BacktestModeComparison,
    BacktestModeDiff,
    BacktestModeSummary,
    ComparisonLimits,
    ComparisonRuntimeSummary,
    ModeTradeDiff,
    NormalizedTradeSummary,
    compare_backtest_reports,
    comparison_to_dict,
    load_backtest_report,
    load_and_compare_backtest_reports,
    load_and_summarize_backtest_report,
    render_comparison_markdown,
)
from .recalculation import (
    IntradaySnapshot,
    RecalculationInput,
    RecalculationResult,
    S23RecalculationEngine,
)
from .s23_current_day_fsl_trp import (
    CurrentDayFslTrpTriggerResult,
    CurrentDaySnapshot,
    S23CurrentDayFslTrpEngine,
    S23CurrentDayFslTrpInput,
    S23CurrentDayFslTrpResult,
)
from .trade_lifecycle import EodExitPolicy, TradeLifecycleResult, TradeLifecycleSimulator
from .monthly_status_context import (
    HistoricalMonthlyStatusContext,
    HistoricalMonthlyStatusSkip,
    MonthlyStatusContextComputation,
    build_monthly_status_context,
    load_monthly_bars_csv,
    load_weekly_bars_csv,
)
from .option_chain import (
    OptionChainContract,
    OptionChainSelector,
    OptionSelectionRequest,
    OptionSelectionResult,
    load_option_chain_csv,
)
from .shared_data_adapter import (
    SharedBacktestDataset,
    discover_shared_data_roots,
    resolve_shared_backtest_dataset,
)

__all__ = [
    "BacktestInput",
    "BacktestCsvError",
    "BacktestReportComparisonError",
    "BacktestMetrics",
    "BacktestModeComparison",
    "BacktestModeDiff",
    "BacktestModeSummary",
    "BacktestRunner",
    "BacktestTradeResult",
    "BacktestValidation",
    "CostModel",
    "CurrentDayFslTrpTriggerResult",
    "CurrentDaySnapshot",
    "ContractIntradayBar",
    "ComparisonLimits",
    "ComparisonRuntimeSummary",
    "EntryMissedInput",
    "EntryMissedResult",
    "ExpiryDayLifecycleReview",
    "HistoricalBacktestMetrics",
    "HistoricalBacktestReport",
    "HistoricalBacktestRunner",
    "HistoricalCandidateResult",
    "HistoricalMarketSnapshot",
    "HistoricalMonthlyStatusContext",
    "HistoricalMonthlyStatusSkip",
    "IntradaySnapshot",
    "MonthlyStatusContextComputation",
    "ModeTradeDiff",
    "NormalizedTradeSummary",
    "OptionChainContract",
    "OptionChainSelector",
    "OptionLevelsSnapshot",
    "OptionSelectionRequest",
    "OptionSelectionResult",
    "SharedBacktestDataset",
    "EodExitPolicy",
    "S23EntryMissedDetector",
    "S23CurrentDayFslTrpEngine",
    "S23CurrentDayFslTrpInput",
    "S23CurrentDayFslTrpResult",
    "TradeLifecycleResult",
    "TradeLifecycleSimulator",
    "ParameterSweepReport",
    "ParameterSweepRankingEntry",
    "ParameterSweepRunner",
    "ParameterSweepSummary",
    "ParameterSweepTradeOutputs",
    "ParameterSweepVariantResult",
    "RecalculationInput",
    "RecalculationResult",
    "S23RecalculationEngine",
    "build_parameter_sweep_ranking",
    "build_backtest_metrics",
    "build_expiry_day_lifecycle_review",
    "build_contract_intraday_lookup",
    "build_monthly_status_context",
    "compare_backtest_reports",
    "comparison_to_dict",
    "load_daily_bars_csv",
    "load_contract_intraday_bars_csv",
    "load_intraday_option_bars_csv",
    "load_intraday_spot_bars_csv",
    "load_monthly_bars_csv",
    "load_option_levels_csv",
    "load_option_levels_series_csv",
    "load_option_chain_csv",
    "load_backtest_report",
    "load_and_compare_backtest_reports",
    "load_and_summarize_backtest_report",
    "discover_shared_data_roots",
    "load_weekly_bars_csv",
    "calculate_risk_reward_metrics",
    "generate_parameter_combinations",
    "render_parameter_sweep_markdown",
    "resolve_shared_backtest_dataset",
    "resolve_contract_intraday_bars",
    "render_comparison_markdown",
    "sample_daily_bars",
    "sample_runtime_values",
]
